[build]
  publish = "."
  command = ""
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# No instalar dependencias - es solo HTML est√°tico
[build.environment]
  NODE_VERSION = "18"
